package load

import (
	"github.com/audioo/goseek/helpers/ent"
)

// NoRedirSites ...
func NoRedirSites(userres string) []ent.Website {
	var arr []ent.Website

	arr = append(arr, ent.Website{Title: "FACEBOOK", Domain: "https://www.facebook.com/" + userres})
	arr = append(arr, ent.Website{Title: "BLOGSPOT", Domain: "https://" + userres + ".blogspot.com"})
	arr = append(arr, ent.Website{Title: "WORDPRESS", Domain: "https://" + userres + ".wordpress.com"})

	return arr
}

// RedirSites ...
func RedirSites(userres string) []ent.Website {
	var arr []ent.Website

	arr = append(arr, ent.Website{Title: "PINTEREST", Domain: "https://www.pinterest.com/" + userres, Delete: "https://pinterest.com/settings/"})
	arr = append(arr, ent.Website{Title: "GITHUB", Domain: "https://www.github.com/" + userres, Delete: "https://github.com/settings/admin"})
	arr = append(arr, ent.Website{Title: "TUMBLR", Domain: "https://" + userres + ".tumblr.com", Delete: "https://www.tumblr.com/account/delete"})
	arr = append(arr, ent.Website{Title: "FLICKR", Domain: "https://www.flickr.com/people/" + userres, Delete: "http://www.flickr.com/profile_delete.gne"})
	arr = append(arr, ent.Website{Title: "VIMEO", Domain: "https://vimeo.com/" + userres, Delete: "https://vimeo.com/settings/goodbye/forever"})
	arr = append(arr, ent.Website{Title: "SOUNDCLOUD", Domain: "https://soundcloud.com/" + userres, Delete: "http://soundcloud.com/settings/account#delete-user"})
	arr = append(arr, ent.Website{Title: "DISQUS", Domain: "https://disqus.com/by/" + userres, Delete: "http://disqus.com/pages/dashboard/#account"})
	arr = append(arr, ent.Website{Title: "MEDIUM", Domain: "https://medium.com/@" + userres, Delete: "https://medium.com/me/settings"})
	arr = append(arr, ent.Website{Title: "DEVIANTART", Domain: "https://" + userres + ".deviantart.com", Delete: "https://www.deviantart.com/settings/deactivation"})
	arr = append(arr, ent.Website{Title: "VK", Domain: "https://vk.com/" + userres, Delete: "http://vk.com/settings?act=deactivate"})
	arr = append(arr, ent.Website{Title: "ABOUTME", Domain: "https://about.me/" + userres, Delete: "https://about.me/account"})
	arr = append(arr, ent.Website{Title: "FLIPBOARD", Domain: "https://flipboard.com/@" + userres, Delete: "https://flipboard.com/support/"})
	arr = append(arr, ent.Website{Title: "SLIDESHARE", Domain: "https://slideshare.net/" + userres, Delete: "N/A"})
	arr = append(arr, ent.Website{Title: "SCRIBD", Domain: "https://www.scribd.com/" + userres, Delete: "http://www.scribd.com/account_settings/preferences"})
	arr = append(arr, ent.Website{Title: "PATREON", Domain: "https://www.patreon.com/" + userres, Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "BITBUCKET", Domain: "https://bitbucket.org/" + userres, Delete: "https://bitbucket.org/account/"})
	arr = append(arr, ent.Website{Title: "DAILYMOTION", Domain: "https://www.dailymotion.com/" + userres, Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "ETSY", Domain: "https://www.etsy.com/shop/" + userres, Delete: "http://www.etsy.com/help/article/53"})
	arr = append(arr, ent.Website{Title: "CASHAPP", Domain: "https://cash.app/$" + userres, Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "BEHANCE", Domain: "https://www.behance.net/" + userres, Delete: "http://www.behance.net/account/privacy"})
	arr = append(arr, ent.Website{Title: "GOODREADS", Domain: "https://www.goodreads.com/" + userres, Delete: "http://www.goodreads.com/user/destroy"})
	arr = append(arr, ent.Website{Title: "INSTRUCTABLES", Domain: "https://www.instructables.com/member/" + userres, Delete: "Email service@instructables.com"})
	arr = append(arr, ent.Website{Title: "KEYBASE", Domain: "https://keybase.io/" + userres, Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "KONGREGATE", Domain: "https://kongregate.com/accounts/" + userres, Delete: "http://www.kongregate.com/forums/7/topics/241772?page=1#posts-5207538"})
	arr = append(arr, ent.Website{Title: "LIVEJOURNAL", Domain: "https://" + userres + ".livejournal.com", Delete: "http://www.livejournal.com/accountstatus.bml"})
	arr = append(arr, ent.Website{Title: "LASTFM", Domain: "https://last.fm/user/" + userres, Delete: "http://www.last.fm/settings/account"})
	arr = append(arr, ent.Website{Title: "DRIBBBLE", Domain: "https://dribbble.com/" + userres, Delete: "http://dribbble.com/account"})
	arr = append(arr, ent.Website{Title: "CODECADEMY", Domain: "https://www.codecademy.com/profiles/" + userres, Delete: "http://help.codecademy.com/customer/portal/articles/1394081-how-do-i-delete-my-account-"})
	arr = append(arr, ent.Website{Title: "GRAVATAR", Domain: "https://en.gravatar.com/" + userres, Delete: "N/A"})
	arr = append(arr, ent.Website{Title: "PASTEBIN", Domain: "https://pastebin.com/u/" + userres, Delete: "N/A"})
	arr = append(arr, ent.Website{Title: "ROBLOX", Domain: "https://www.roblox.com/user.aspx?username=" + userres, Delete: "N/A"})
	arr = append(arr, ent.Website{Title: "GUMROAD", Domain: "https://www.gumroad.com/" + userres, Delete: "https://gumroad.com/settings"})
	arr = append(arr, ent.Website{Title: "NEWGROUNDS", Domain: "https://" + userres + ".newgrounds.com", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "WATTPAD", Domain: "https://www.wattpad.com/user/" + userres, Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "TRAKT", Domain: "https://www.trakt.tv/users/" + userres, Delete: "http://trakt.tv/settings/data"})
	arr = append(arr, ent.Website{Title: "BUZZFEED", Domain: "https://buzzfeed.com/" + userres, Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "TRIPADVISOR", Domain: "https://www.tripadvisor.com/Profile/" + userres, Delete: "https://www.tripadvisorsupport.com/hc/en-us/articles/200615117"})
	arr = append(arr, ent.Website{Title: "HUBPAGES", Domain: "https://" + userres + ".hubpages.com", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "BLIPFM", Domain: "https://blip.fm/" + userres, Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "WIKIPEDIA", Domain: "https://en.wikipedia.org/wiki/User:" + userres, Delete: "https://en.wikipedia.org/wiki/Wikipedia:FAQ#How_do_I_change_my_username.2Fdelete_my_account.3F"})
	arr = append(arr, ent.Website{Title: "CODEMENTOR", Domain: "https://www.codementor.io/" + userres, Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "REVERBNATION", Domain: "https://www.reverbnation.com/" + userres, Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "DESIGNSPIRATION", Domain: "https://www.designspiration.com/" + userres, Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "BANDCAMP", Domain: "https://www.bandcamp.com/" + userres, Delete: "https://bandcamp.com/settings?pane=fan"})
	arr = append(arr, ent.Website{Title: "COLOURLOVERS", Domain: "https://www.colourlovers.com/lover/" + userres, Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "IFTTT", Domain: "https://www.ifttt.com/p/" + userres, Delete: "https://ifttt.com/settings/deactivate"})
	arr = append(arr, ent.Website{Title: "SLACK", Domain: "https://" + userres + ".slack.com", Delete: "https://my.slack.com/account/settings"})
	arr = append(arr, ent.Website{Title: "ELLO", Domain: "https://ello.co/" + userres, Delete: "https://ello.co/delete-account"})
	arr = append(arr, ent.Website{Title: "7CUPS", Domain: "https://www.7cups.com/@" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "INDEPENDENT ACADEMIA", Domain: "https://independent.academia.edu/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "ALIK", Domain: "https://www.alik.cz/u/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "AUDIO JUNGLE", Domain: "https://audiojungle.net/user/" + userres + "", Delete: "https://help.market.envato.com/hc/en-us/articles/202500394-How-Do-I-Close-My-Account-"})
	arr = append(arr, ent.Website{Title: "BOOK CROSSING", Domain: "https://www.bookcrossing.com/mybookshelf/" + userres + "/", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "BUY ME A COFFEE", Domain: "https://buymeacoff.ee/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "CNET", Domain: "https://www.cnet.com/profiles/" + userres + "/", Delete: "https://cbsi.secure.force.com/CBSi/submitcase?template=template_cnet&referer=cnet.com&cfs=SFS_1"})
	arr = append(arr, ent.Website{Title: "CARBONMADE", Domain: "https://" + userres + ".carbonmade.com", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Chess", Domain: "https://www.chess.com/member/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "CodeWars", Domain: "https://www.codewars.com/users/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Countable", Domain: "https://www.countable.us/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "DevTo", Domain: "https://dev.to/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Discogs", Domain: "https://www.discogs.com/user/" + userres + "", Delete: "http://www.discogs.com/users/delete"})
	arr = append(arr, ent.Website{Title: "Eyeem", Domain: "https://www.eyeem.com/u/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "F3", Domain: "https://f3.cool/" + userres + "/", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Fortnite Tracker", Domain: "https://fortnitetracker.com/profile/all/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "FreeSound", Domain: "https://freesound.org/people/" + userres + "/", Delete: "http://www.freesound.org/home/delete/"})
	arr = append(arr, ent.Website{Title: "GameSpot", Domain: "https://www.gamespot.com/profile/" + userres + "/", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Giphy", Domain: "https://giphy.com/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Gitlab", Domain: "https://gitlab.com/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "GuruShots", Domain: "https://gurushots.com/" + userres + "/photos", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Hackaday", Domain: "https://hackaday.io/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "HackerOne", Domain: "https://hackerone.com/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Houzz", Domain: "https://houzz.com/user/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Issuu", Domain: "https://issuu.com/" + userres + "", Delete: "https://issuu.com/home/settings/billing"})
	arr = append(arr, ent.Website{Title: "Itch", Domain: "https://" + userres + ".itch.io/", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Jimdosite", Domain: "https://" + userres + ".jimdosite.com", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "LeetCode", Domain: "https://leetcode.com/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Letterboxd", Domain: "https://letterboxd.com/" + userres + "", Delete: "http://letterboxd.com/user/disableaccount/"})
	arr = append(arr, ent.Website{Title: "Lichess", Domain: "https://lichess.org/@/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Memrise", Domain: "https://www.memrise.com/user/" + userres + "/", Delete: "http://www.memrise.com/settings/deactivate/"})
	arr = append(arr, ent.Website{Title: "Munzee", Domain: "https://www.munzee.com/m/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "My Anime List", Domain: "https://myanimelist.net/profile/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "My Mini Factory", Domain: "https://www.myminifactory.com/users/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "MySpace", Domain: "https://myspace.com/" + userres + "", Delete: "https://myspace.com/settings/profile"})
	arr = append(arr, ent.Website{Title: "Periscope", Domain: "https://www.periscope.tv/" + userres + "/", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Pink Bike", Domain: "https://www.pinkbike.com/u/" + userres + "/", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Pokemon Showdown", Domain: "https://pokemonshowdown.com/users/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Product Hunt", Domain: "https://www.producthunt.com/@" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "PromoDJ", Domain: "http://promodj.com/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "PyPi", Domain: "https://pypi.org/user/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Rajce", Domain: "https://" + userres + ".rajce.idnes.cz/", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Rate Your Music", Domain: "https://rateyourmusic.com/~" + userres + "", Delete: "http://rateyourmusic.com/account/delete"})
	arr = append(arr, ent.Website{Title: "Red Bubble", Domain: "https://www.redbubble.com/people/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Repl.it", Domain: "https://repl.it/@" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Sbazar", Domain: "https://www.sbazar.cz/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Shitpost Bot", Domain: "https://www.shitpostbot.com/user/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Smule", Domain: "https://www.smule.com/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "SourceForge", Domain: "https://sourceforge.net/u/" + userres + "", Delete: "https://sourceforge.net/auth/disable/"})
	arr = append(arr, ent.Website{Title: "Speedrun", Domain: "https://speedrun.com/user/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Roberts Space Industries", Domain: "https://robertsspaceindustries.com/citizens/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Tellonym", Domain: "https://tellonym.me/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "TikTok", Domain: "https://tiktok.com/@" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Trading View", Domain: "https://www.tradingview.com/u/" + userres + "/", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Ultimate Guitar", Domain: "https://ultimate-guitar.com/u/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Unsplash", Domain: "https://unsplash.com/@" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "VSCO", Domain: "https://vsco.co/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Vero", Domain: "https://vero.co/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "WarriorForum", Domain: "https://www.warriorforum.com/members/" + userres + ".html", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "We Heart It", Domain: "https://weheartit.com/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Windy", Domain: "https://community.windy.com/user/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "XBox", Domain: "https://xboxgamertag.com/search/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Zhihu", Domain: "https://www.zhihu.com/people/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "All My Links", Domain: "https://allmylinks.com/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Couch Surfing", Domain: "https://www.couchsurfing.com/people/" + userres + "", Delete: "https://www.couchsurfing.org/delete_profile.html?delete=1"})
	arr = append(arr, ent.Website{Title: "DailyKOs", Domain: "https://www.dailykos.com/user/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Dating", Domain: "http://dating.ru/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Drive2", Domain: "https://www.drive2.ru/users/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "FL", Domain: "https://www.fl.ru/users/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Geocaching", Domain: "https://www.geocaching.com/p/default.aspx?u=" + userres + "", Delete: "http://support.groundspeak.com/index.php?pg=kb.page&id=102"})
	arr = append(arr, ent.Website{Title: "Gfycat", Domain: "https://gfycat.com/@" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Hackster", Domain: "https://www.hackster.io/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Irecommend", Domain: "https://irecommend.ru/users/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "JBZD", Domain: "https://jbzd.com.pl/uzytkownik/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "JeuxVideo", Domain: "http://www.jeuxvideo.com/profil/" + userres + "?mode=infos", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Kwork", Domain: "https://kwork.ru/user/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Livelib", Domain: "https://www.livelib.ru/reader/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Moikrug", Domain: "https://moikrug.ru/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Nairaland", Domain: "https://www.nairaland.com/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "NN", Domain: "https://" + userres + ".www.nn.ru/", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Note", Domain: "https://note.com/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "NPMJS", Domain: "https://www.npmjs.com/~" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Osu", Domain: "https://osu.ppy.sh/users/" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "Pikabu", Domain: "https://pikabu.ru/@" + userres + "", Delete: "TODO"})
	arr = append(arr, ent.Website{Title: "TOSTER", Domain: "https://www.toster.ru/user/" + userres + "/answers", Delete: "TODO"})

	return arr
}
